# @createby: teachmyself@126.com
# @reference:
#       https://hub.docker.com/_/mongo
#       https://hub.docker.com/_/mongo-express
#       https://github.com/YMFE/yapi
---
version: '3'
networks:
  netyapi:

services:
  yapi-mongo:
    networks:
      - netyapi
    container_name: yapi-mongo
    hostname: yapi-mongo
    #image: icmdb/mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=YapiMongoPassw0rd
      - MONGO_INITDB_DATABASE=yapi
    ports: 
      - 27017:27017
    volumes:
      - ./yapi-mongodata/db:/data/db
    restart: always

  yapi-mongo-express:
    networks:
      - netyapi
    container_name: yapi-mongo-express
    hostname: yapi-mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo.loc.icmdb.vip
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=YapiMongoPassw0rd
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=YapiMongoExpressPassw0rd
      #- ME_CONFIG_SITE_COOKIESECRET=YapiMongoExpressCookieSecret
      #- ME_CONFIG_SITE_SESSIONSECRET=YapiMongoExpressSessionSecret
      #- ME_CONFIG_OPTIONS_READONLY=0
    ports:
      - 8081:8081
    links:
      - yapi-mongo:mongo.loc.icmdb.vip
    restart: always
    
  yapi:
    networks:
      - netyapi
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: yapi
    hostname: yapi
    image: icmdb/yapi
    environment:
      - YAPI_DEBUG=1
      - YAPI_DELAY=3
      - YAPI_PORT=3000
      - YAPI_ACOUNT=admin@icmdb.vip
      - YAPI_DB_HOST=mongo.loc.icmdb.vip
      - YAPI_DB_NAME=yapi
      - YAPI_DB_PORT=27017
      - YAPI_DB_USER=root
      - YAPI_DB_PASS=YapiMongoPassw0rd
      - YAPI_DB_AUTH=admin
      - YAPI_MAIL_ENABLE=true
      - YAPI_MAIL_HOST=smtpdm.aliyun.com
      - YAPI_MAIL_PORT=465
      - YAPI_MAIL_FROM=notice@mail.icmdb.vip
      - YAPI_MAIL_USER=YAPI_MAIL_FROM
      - YAPI_MAIL_PASS=bm90aWNlQG1haWwuaWNt
    ports:
      - 3000:3000
    volumes:
      - ./yapi-log/log/:/app/yapi/log/
    links:
      - yapi-mongo:mongo.loc.icmdb.vip
    restart: on-failure
