---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yapi-yapi
  name: yapi-yapi
  namespace: icmdb-yapi
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app: yapi-yapi
  type: NodePort
#  type: ClusterIP
